Laravel scheduling&data transformation
Webdev-Breman/BremanAPI pull request #26
Opened 2022-06-15 07:27 UTC by streikbaut

2022-06-15 09:25 UTC, Tj33rd approved these changes

2022-06-15 09:25 UTC, Tj33rd commented on api/app/Console/Kernel.php
> +        $schedule->command('UpdatePumps:Auto')->everyMinute();
I think every minute because of testing?

2022-06-15 09:25 UTC, Tj33rd commented on api/app/Http/Controllers/AutomaticDataController.php
> +            }
```suggestion
$service = new ApiService($request->input('api_type'));
$response = $service->api->Normalize();
if(in_array($pumps['id'], $pumps_in_datasets)){
$this->UpdateDataSet($response)
} else {
$this->InsertDataSet($response)
}
```

The reason you want to move the normalization out of this file, is to make it easier to edit and add other api's. Otherwise you need to add cases for every new api. And also, if you want to use the normalization somewhere else, you have to use the samecode. So it makes it more DRY. 

To implement this, you will probably need to change the existing normalization because the database has had an update.

2022-06-15 09:27 UTC, Tj33rd requested changes
Wrong button on last review :)

2022-06-15 10:40 UTC, streikbaut commented on api/app/Console/Kernel.php
> +        $schedule->command('UpdatePumps:Auto')->everyMinute();
Yes, changed to hourly

2022-06-17 09:49 UTC, Tj33rd approved these changes

2022-06-17 09:49 UTC, merged