Feat/warnings
Webdev-Breman/BremanAPI pull request #34
Opened 2022-06-23 11:08 UTC by Tj33rd

2022-06-23 11:14 UTC, streikbaut commented on api/app/Http/Controllers/HeatPumpController.php
> +        $normalizedResult = $service->api->normalize(json_decode($result,true));
This change results in an error when running the automatic data retrieval

2022-06-23 11:15 UTC, streikbaut commented on api/app/Libraries/Services/ApiService/API/SwycsApi.php
> +        $normalizedArray['pressure_CV'] = $this->FindField($fields, 'Heating Circuit Pressure');
This results in an error when running the automatic data retrieval

2022-06-23 11:17 UTC, MatzLeeflang submitted a review, later dismissed

2022-06-23 11:20 UTC, streikbaut requested changes
Automatic data retrieval has been broken by some changes

2022-06-24 06:16 UTC, MatzLeeflang approved these changes

2022-06-24 08:01 UTC, streikbaut approved these changes

2022-06-24 08:04 UTC, merged